modLoader="javafml"
loaderVersion="[43,)"
license="Attribution-NonCommercial-ShareAlike 3.0 Unported"
issueTrackerURL="https://github.com/CERBON-MODS/CERBONs-Better-Beacons-FORGE/issues" #optional

[[mods]]
modId="better_beacons"
version="${file.jarVersion}"
displayName="CERBON's Better Beacons"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cerbons-better-beacons-forge"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="CerbonXD"
description='''New UI, new features and new advancements. Improves Minecraft's beacon.'''

[[dependencies.better_beacons]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.better_beacons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"
